apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m5km4k43n-go 
  janus-idp.io/tekton: m5km4k43n-go
  backstage.io/kubernetes-id: m5km4k43n-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m5km4k43n-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  